### ISSUE TITLE
COOK-4094 : python_pip resource(s) for packages have no support for pip options

### ISSUE THREAD

**Issue by jblaine** [poise/application_python#37]
python_pip has the 'options' attribute

This option is not catered to in the protected install_packages() in providers.rb ( https://github.com/poise/application_python/blob/master/providers/django.rb#L111 )

I cannot, therefore, install any pip packages as I am behind an HTTP proxy. And so I am dead in the water and not sure what the right/acceptable approach to the code would be.

Reported here: https://tickets.opscode.com/browse/COOK-4094

**Comment by jmaziarz** [comment]
+1

**Comment by coderanger** [comment]
This is no longer an issue as the underlying resource is exposed more directly.
