### ISSUE TITLE
COOK-4059: application_python's gunicorn.rb attempts to install requirements attached to django block as root, system-wide, outside of the virtualenv

### ISSUE THREAD

**Issue by micolous** [poise/application_python#43]
When attempting to install a Django application using application_python, with a recipe based on the `packaginator` example, the recipe will install requirements listed in the `django` block as follows:

* 1st: From `django.rb`, install the requirements inside `django`'s Virtualenv, as the `owner` in the `application` block, using the `GIT_SSH` wrapper if one is specified
* 2nd: From `gunicorn.rb`, install the requirements inside `django` block, as `root`, system-wide (outside of Virtualenv).

It appears that there is some code that attempts to pull in Virtualenv details from the `django` block if `app_module == :django`, but this doesn't seem to be used properly in `providers/gunicorn.rb` line 135-140.
Also, `git` may refuse to use the wrapper script as `root` if it is owned by a different `application.owner`.

This is a problem because it means:
- Everything in the requirements.txt file is installed twice (once in the virtualenv and once system-wide)
- The system-wide installation cannot pull from SSH-based git repositories.

This means that code stored in private repositories referenced from a `requirements.txt` on GitHub/Bitbucket/whatever (`git+ssh`) will fail to install and have an error of `Permission denied (publickey)`.

As a workaround in my recipe, I've put in the `gunicorn` block `reqirements false`.  This seems to prevent `gunicorn.rb` from trying to install any dependencies, or try to be smart by looking for `requirements.txt` at the root of the repository.

If this is all intended behaviour, then maybe the example for `packaginator` should be updated and this behaviour be documented.

**Comment by coderanger** [comment]
This has been corrected.
