### ISSUE TITLE
manage.py syncdb --noinput fails to run

### ISSUE THREAD

**Issue by richardbowden** [poise/application_python#46]
during a chef run syncdb fails to run. this is the error, i cannot see what is causing this... any ideas ? cheers

Chef::Exceptions::Exec: deploy_revision[datagether](/var/chef/cache/cookbooks/application/providers/default.rb line 122) had an error: Chef::Exceptions::Exec: /home/wolfpack/datagether/shared/env/bin/python manage.py syncdb --noinput returned 1, expected 0

**Comment by Carpetfizz** [comment]
Hey @richardbowden, did you ever figure out what was causing your error?

**Comment by jwmarshall** [comment]
FWIW I had a problem recently where a newly bootstrapped node installed chef 12 which caused unexpected errors with a deploy_revision resource. I don't have the logs unfortunately.

**Comment by richardbowden** [comment]
Hello @Carpetfizz, i spent a few days on it not getting anywhere, in the end i ditched the this cookbook and crafted a recipe specific for my app as I had to get the app deployed...

**Comment by richardbowden** [comment]
@Carpetfizz i have just checked my cookbooks, i did get it working post deployment just to satisfy my self...here the is recipe, if i remember correctly, i had to set the sync command manually as you can see from http://pastebin.com/9NpvNUui hope this may help a little

**Comment by Carpetfizz** [comment]
Thanks much, I'll check it out!
