### ISSUE TITLE
Possible fix for virtualenv references

### ISSUE THREAD

**Issue by jwmarshall** [poise/application_python#50]
I spent some time thinking about how to solve the virtualenv issues with gunicorn installing on the host vs the virtualenv associated with the (django) application.

If we modify the resource to support a symbol argument we can use that symbol to identify another resource in the application resource. As an example you could specify a virtualenv of :django to install to the same virtualenv as that resource.

Check my commit here:
https://github.com/BNOTIONS/application_python/commit/a65a9e6fa613b3b31e02c186136e46573160f971

**Comment by coderanger** [comment]
This should all be corrected now, gunicorn is installed into which python environment the app is using.
