### ISSUE TITLE
Writing Test with Kitchen

### ISSUE THREAD

**Issue by Little-Black** [poise/application_python#57]
I'm working on adding test suites to this application_python cookbook, and mainly focus on testing deploying django application using this cookbook. 
Forked to [OpenAcademyChefs/application_python]
(https://github.com/OpenAcademyChefs/application_python/tree/tests)

**Comment by Little-Black** [comment]
* test suite default:
deploying an empty application
(Passed)
* test suite django_init:
deploying a sample [django application](https://github.com/OpenAcademyChefs/sample-django)
(Failing)

**Comment by coderanger** [comment]
Not sure what the question was here.
