### ISSUE TITLE
dependency on 'application' cookbook '~> 3.0' prevents Chef 12 runs

### ISSUE THREAD

**Issue by shaneramey** [poise/application_python#58]
The application cookbook required by this cookbook has a fix for Chef 12 in version 4.1.6 https://github.com/poise/application/issues/53. Since application_python has a dependency on 3.x, this fix for Chef 12 wasn't implemented.

**Comment by jblaine** [comment]
+1

application_python depends on application 3.0.0 which has no fix for Chef 12 per poise/application#53 :(

**Comment by jblaine** [comment]
@coderanger Hi Noah. I'm not sure if this cookbook is being worked on as part of Bloomberg's funded development for the poise stuff, but everything's in a such a (understandable) state of rework, that outsiders contributing a fix for this seems unreasonable. With Chef 12 everywhere, we're sort of dead in the water here for deploying any new versions of our application_python-controlled stuff. That's ultimately our fault, of course, through lack of proper testing. I'm curious to know though if you have a rough idea of how far ahead a fix for this might come through (again, assuming you're being paid to work on it)?

@shaneramey Did you develop a workaround? Best I can come up with is special-casing affected hosts to stay at Chef 11 while our other ~1300 hosts run 12.

Respectfully - Jeff

**Comment by coderanger** [comment]
@jblaine Master of both this and the `application` cookbook are Chef 12 compatible (in fact they only support Chef 12). They will both be released shortly once I've let `poise-python` and friends soak in the community for a few days.

**Comment by jblaine** [comment]
It would be fantastic to have a final release of this functioning under Chef 12 and not requiring redoing everything to the new poise/application

**Comment by coderanger** [comment]
@jblaine That will not be happening. Closing this out as things are ready to go for release.
