### ISSUE TITLE
How to add settings to local_settings.py?

### ISSUE THREAD

**Issue by rberger** [poise/application_python#59]
In the old `application_python` `django` resource, you could specify your own `settings.py.erb` and pass in variables for it in `additional_settings` resource attribute. How would one do this with the new `poise/application_python`?

**Comment by coderanger** [comment]
```ruby
django do
  local_settings_source 'settings.py.erb'
  local_settings_options foo: 'bar'
end
```

**Comment by rberger** [comment]
Nice. Maybe add to Readme? Or is there somewhere I missed all the resource attributes described that includes that?

**Comment by coderanger** [comment]
This is now in the readme a bit better.

**Comment by nadobando** [comment]
not working for me
