### ISSUE TITLE
Is current master branch usable?

### ISSUE THREAD

**Issue by issue2k** [poise/application_python#61]
First, thank you for your work. I am new to chef and i am currently implementing a new cookbook to deploy our django based applications. As the last release is 3.0.0 and it fundamentally differs from the current implementation in the master branch i am wondering if i can use the version in master branch already. I tried to include it via the git repo but chef complains about the missing metadata.rb. So my question is: should i use the old version 3.0.0 or the current master branch? If i can use the master branch, how is that possible?

Thanks much for your help!
Jakob

**Comment by coderanger** [comment]
Yep, should be ready to rock. I just released the `poise-python` cookbook yesterday so letting that soak for a day or two before I release this and the other `application_*` work I've been hammering on for the past 6 months. Keep in mind this is a Halite-based cookbook so you'll need to follow https://github.com/poise/halite#using-a-pre-release-version-of-a-cookbook to run from master.

**Comment by issue2k** [comment]
Great, thanks!
