### ISSUE TITLE
Understanding 4.0.0 'local_settings'

### ISSUE THREAD

**Issue by jblaine** [poise/application_python#66]
Having read the poise-developer-centric link to "Poise template property" I don't really understand how to use `local_settings`:

local_settings – A Poise template property for the content of the local settings configuration file.

Can someone shed some more light on the topic?

```
  NoMethodError
  -------------
  undefined method `local_settings' for PoiseApplicationPython::Resources::Django::Resource
```
```
   40:    django do
   41:      migrate false
   42>>     local_settings 'settings.py.erb'
   43:      debug true
   44:      database do
   45:        host 'hostdb'
   46:        database 'hostdb'
   47:        adapter  'mysql'
   48:        username chef_vault_item('secrets', 'hostdb')['username']
   49:        password chef_vault_item('secrets', 'hostdb')['password']
   50:        time_zone 'America/New_York'
   51:      end
```

**Comment by coderanger** [comment]
Template content properties are a Poise feature to combine template-like and file-like behaviors. You end up with a few actual properties: `local_settings_source`, `local_settings_options`, and `local_settings_content` being the important ones. The first two are like `source` and `variables` on a template resource and the latter is like `content` on a file resource. You can set either one side or the other. By default it uses an internal template to generate the local settings file, https://github.com/poise/application_python/blob/master/chef/templates/settings.py.erb. I would probably use that as a starting point for any modifications.

**Comment by jblaine** [comment]
Thanks. That got me sorted out.

**Comment by jblaine** [comment]
Or not :(

Getting back to this today to actually try it now that the other problems I had are unstuck, I am finding that the following does not render the template specified (so I am probably still not understanding this).

`templates/default/settings.py.erb` exists in the cookbook, and here's how I am trying to refer to it:

```
...
  django do
    migrate false
    local_settings_source 'settings.py.erb'
    debug true
...
    end
  end
```

I am expecting that to render a settings file using `templates/default/settings.py.erb` as the source.

Instead, I get this error:

```
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of ["/root/hostdb.new/.virtualenv/bin/python", "/root/hostdb.new/manage.py", "collectstatic", "--noinput"] ----
      STDOUT:
      STDERR: Traceback (most recent call last):
        File "/root/hostdb.new/manage.py", line 9, in <module>
          execute_from_command_line(sys.argv)
        File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
          utility.execute()
        File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
          self.fetch_command(subcommand).run_from_argv(self.argv)
        File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 263, in fetch_command
          app_name = get_commands()[subcommand]
        File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 109, in get_commands
          apps = settings.INSTALLED_APPS
        File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
          self._setup(name)
        File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
          self._wrapped = Settings(settings_module)
        File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/__init__.py", line 134, in __init__
          raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
      ImportError: Could not import settings 'settings' (Is it on sys.path?): No module named settings
```

And there is no settings file rendered

```
~:rcf-webapps# find hostdb.new -name \*settings\*
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/commands/diffsettings.py
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/commands/diffsettings.pyc
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/project_template/project_name/settings.py
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/project_template/project_name/settings.pyc
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/global_settings.py
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/global_settings.pyc
~:rcf-webapps#
```

**Comment by jblaine** [comment]
Adding `local_settings_options ({:whatever => 'foo'})` doesn't help me along any further. I thought I'd try that to see if maybe it needed some options passed to the template to trigger/tickle something into working.

Eventually, yes, I'll pass real 'options' into the template.

**Comment by coderanger** [comment]
If you don't have a `settings.py` in the app at all, you'll need to manually tell it where write the settings out. The expected use case is that you'll have a standard settings file in the app repo/package which tries to `from local_settings import *`. This is the closet thing Django has to a standard for env-specific config right now. Is your goal the the `django` resource entirely manages the settings file?

**Comment by jblaine** [comment]
We're kind of in the middle, frankly. We have settings.py but it's not part of the repo due to it needing to be different in a few spots depending on the overall Django app's usage+location. Clearly that's a sign of some poor design somewhere. I'm not a Real Django Developer. The proper usage/pattern for settings.py et al has been unclear to me from the start, and I sure don't expect you to spend your valuable time explaining it to me :) I'm seeing now from your brief explanation that our per-environment specifics ("usage+location" above) should be `local_settings.py` and it sounds like I need to put some time back into the Django docs since 5 years ago.

However, we're really just trying to get this *pre-poise* application working again since moving to Chef 12 some time ago and the older application_python (or something, I forget which piece) not supporting Chef 12. Ideally without redoing Django stuff, but that may be necessary after all.

For this recipe and intent (the actual web app, vs CLI tools under manage.py's framework), we're fine with the django resource entirely managing the settings file, so that's what I was trying to do. Previously we were just using `template`. I was just trying to be poise+application-CB-idiomatic via the "Template content properties". I see now it seems our Django code is not up to snuff with the modern practices which `application_python` is targeting with this feature.

Turns out, trying to backpedal to `template` called within `application` is resulting in the same Python error and no settings.py actually existing on disk, so I'm clearly doing something wrong there too!

```
application '/root/hostdb.new' do
...
  template 'settings.py'

  django do
...
    # no local_settings_* here
...
    end
  end
end
```

```
  * template[settings.py] action create
    - create new file settings.py
    - update content in file settings.py from none to 453876
    --- settings.py     2016-01-07 16:20:03.000000000 -0500
    +++ ./.settings.py20160107-24856-8prb6e     2016-01-07 16:20:03.000000000 -0500
    @@ -1 +1,159 @@
...
    +        },
    +    }
    +}
  * application_django[/root/hostdb.new] action deploy
    * python_execute[manage.py collectstatic --noinput] action run
      [execute] Traceback (most recent call last):
                  File "/root/hostdb.new/manage.py", line 9, in <module>
                    execute_from_command_line(sys.argv)
                  File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
                    utility.execute()
                  File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
                    self.fetch_command(subcommand).run_from_argv(self.argv)
                  File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 263, in fetch_command
                    app_name = get_commands()[subcommand]
                  File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 109, in get_commands
                    apps = settings.INSTALLED_APPS
                  File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
                    self._setup(name)
                  File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
                    self._wrapped = Settings(settings_module)
                  File "/root/hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/__init__.py", line 134, in __init__
                    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
                ImportError: Could not import settings 'settings' (Is it on sys.path?): No module named settings
...
~:rcf-webapps# find hostdb.new -name \*settings\*
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/commands/diffsettings.py
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/core/management/commands/diffsettings.pyc
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/project_template/project_name/settings.py
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/project_template/project_name/settings.pyc
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/global_settings.py
hostdb.new/.virtualenv/lib/python2.7/site-packages/django/conf/global_settings.pyc
~:rcf-webapps# pwd

```

**Comment by jblaine** [comment]
I see:

```
~:rcf-webapps# rm /settings.py
~:rcf-webapps#
```

So being in the context of `application '/root/hostdb.new'` doesn't set CWD to there for enclosed core resources.

**Comment by coderanger** [comment]
Okay, so to make the app_django resource write out the full settings.py here is the voodoo for youdo:

```ruby
django do
  local_settings_path 'myapp/settings.py' # Or where ever you want it to write
  local_settings_source 'settings.py.erb'
  # settings_module 'myapp.settings' # You might need this but I think it should evaluate lazily enough for the above to work
end
```

**Comment by coderanger** [comment]
And yes, there is nothing automatic about the app path. Everywhere that does app-relative paths I needed to handle on my code's side. Core Chef resources behave exactly as normal. You could make an `application_template` resource with auto-relative-ing behavior though, that's how I handle overriding other things.

**Comment by jblaine** [comment]
Thanks Noah. I'm *actually* sorted out here now.
```
  cookbook_file '/root/hostdb.new/settings.py' do
    source 'settings_webapp.py'
  end

  django do
    migrate false
    debug true
    database do
      local_settings_source 'local_settings.py.erb'
...
```

**Comment by parhamfh** [comment]
Hi @coderanger! You write that _"the expected use case is that you'll have a standard settings file in the app repo/package which tries to from local_settings import *. "_ 
Could I ask where the expected use case is documented? We are using your cookbooks (thanks!) and if there are suggested use cases and best practices I would love to read about these :)
