### ISSUE TITLE
gunicorn resource "config" option breaks things?

### ISSUE THREAD

**Issue by jblaine** [poise/application_python#68]
Does anyone have any thoughts how to debug this?

```
  gunicorn do
    app_module 'hostdb.wsgi'
    port 9999
    config "/root/hostdb.new/gunicorn_config.py"
  end
```

This results in the service failing due to too many respawns:

```
Jan 28 17:17:53 rcf-webapps init: hostdb.new main process (5075) terminated with status 1
Jan 28 17:17:53 rcf-webapps init: hostdb.new main process ended, respawning
...
Jan 28 17:17:55 rcf-webapps init: hostdb.new respawning too fast, stopped
```

```
# hostdb.new generated by poise-service for poise_service[/root/hostdb.new]

description "hostdb.new"

start on runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 10 5
umask 022
chdir /root/hostdb.new
env DJANGO_SETTINGS_MODULE="hostdb.settings"
env PATH="/opt/rh/python27/root/usr/bin:/usr/lib/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/bin:/bin:/sbin:/usr/sbin:/usr/rcf-krb5/bin:/root/bin:/opt/chef/embedded/bin:/opt/chef/embedded/bin"
env LD_LIBRARY_PATH="/opt/rh/python27/root/usr/lib64"
env MANPATH="/opt/rh/python27/root/usr/share/man:"
env XDG_DATA_DIRS="/opt/rh/python27/root/usr/share"
env PKG_CONFIG_PATH="/opt/rh/python27/root/usr/lib64/pkgconfig"

exec /opt/chef/embedded/bin/ruby -e 'Process::UID.change_privilege("apache"); ENV["HOME"] = Dir.home("apache") rescue nil; exec(*["/root/hostdb.new/.virtualenv/bin/python", "-m", "gunicorn.app.wsgiapp", "--config", "/root/hostdb.new/gunicorn_config.py", "--bind", "0.0.0.0:9999", "hostdb.wsgi"])'
```

If I run `gunicorn --config /root/hostdb.new/gunicorn_config.py --bind 0.0.0.0:9999 hostdb.wsgi` by hand, it works.

If I comment out the 'config' property in the resource definition, everything works (but without the desired configuration as indicated in the gunicorn config file of course).

The config file contents are:
```
syslog = True
syslog_prefix = "hostdb_gunicorn"
syslog_facility = "daemon"
loglevel = "info"
errorlog = "/var/log/gunicorn_error.log"
accesslog = "/var/log/gunicorn_access.log"
worker_class = 'gevent'
```
I have to believe then that something is wrong with the generated upstart init file?

**Comment by coderanger** [comment]
Check file permissions maybe? Also make sure it works with SCL, not the system Python: `scl enable python27 'gunicorn --config /root/hostdb.new/gunicorn_config.py --bind 0.0.0.0:9999 hostdb.wsgi'`

**Comment by jblaine** [comment]
Everything's owned by Apache (the whole tree). Using SCL the command runs fine as well.

```
application '/root/hostdb.new' do
  owner 'apache'
  group 'apache'

  python '2.7' do
    provider :scl
  end

  git do
    user 'apache'
    group 'apache'
    repository 'git@gitlab.our.org:R701-Tools/r701-hostdb.git'
    # revision   'master'
    revision   'django18'
    deploy_key chef_vault_item('secrets', 'hostdb-deploy')['private_key']
  end

  virtualenv do
    system_site_packages true
    user 'apache'
  end

  python_package 'django' do
    version '1.8.8'
  end

  python_package 'django-tastypie'
  python_package 'MySQL-python'
  python_package 'python-ldap'
  python_package 'gevent'

  template '/root/hostdb.new/hostdb/settings.py' do
    source 'settings_webapp.py.erb'
    owner 'apache'
    group 'apache'
    mode '0644'
    variables({
                :username => chef_vault_item('secrets', 'hostdb')['username'],
                :password => chef_vault_item('secrets', 'hostdb')['password']
             })
  end

  django do
    migrate false
    collectstatic true
    debug true
  end

  cookbook_file "/root/hostdb.new/gunicorn_config.py" do
    owner 'apache'
    group 'apache'
    mode '0644'
  end

  gunicorn do
    app_module 'hostdb.wsgi'
    port 9999
    config "/root/hostdb.new/gunicorn_config.py"
  end

end
```

**Comment by coderanger** [comment]
What happens if you run the `/opt/chef/embedded/bin/ruby -e 'Process::UID.change_privilege("apache"); ENV["HOME"] = Dir.home("apache") rescue nil; exec(*["/root/hostdb.new/.virtualenv/bin/python", "-m", "gunicorn.app.wsgiapp", "--config", "/root/hostdb.new/gunicorn_config.py", "--bind", "0.0.0.0:9999", "hostdb.wsgi"])'` command from a console? (you might need to run that whole thing with scl enable)

**Comment by jblaine** [comment]
If I manually change the upstart config to have a final line of the following, it works:

`exec /root/hostdb.new/.virtualenv/bin/python -m gunicorn.app.wsgiapp --bind 0.0.0.0:9999 --config /root/hostdb.new/gunicorn_config.py hostdb.wsgi`

**Comment by jblaine** [comment]
ah HA

Log file permissions from a previous non-apache run!

`Error: Error: '/var/log/gunicorn_error.log' isn't writable [IOError(13, 'Permission denied')]`

**Comment by coderanger** [comment]
Yeah, the weird Ruby shim is because older versions of Upstart didn't support specifying a user to run as, so you were testing running it as root there. Going to close this out :)

**Comment by jblaine** [comment]
Thanks yet again, Noah. At least I know how to debug the upstart part if there's a next time. Looks like I need to spend some time with man -s 5 init to figure out how to have made that permission denied error visible somewhere.

**Comment by coderanger** [comment]
I don't know if you are on Ubuntu 12.04 or EL6, but the version of Upstart in both is total rubbish. I use it by default because it seems like the least surprising thing to do but I would highly recommend Supervisord or Runit, or upgrading to an OS with a more recent Upstart :)

**Comment by jblaine** [comment]
CentOS 6. Duly noted.
