### ISSUE TITLE
Application environment not carried over to Django resource

### ISSUE THREAD

**Issue by mattlqx** [poise/application_python#70]
I use an environment variable in my `manage.py` to determine a specific set of credentials to load. It appears that the `environment` attribute of the `application` resource isn't used by the `django` resource as it has no impact on the django python commands that are execute for `collectstatic` and `migrate`.

Here's the example recipe:
```
application release_dir do
  python '2.7'
  environment ({
    :SITE_CONFIG => deploy_bag.fetch('default_site_config', 'abc'),
  })
...
  django do
    path release_dir
    collectstatic true
    local_settings_path false
    migrate false
  end
end
```

I don't get a SITE_CONFIG environment variable when manage.py is run from these resources.

**Comment by coderanger** [comment]
Make that `environment.update()` and it should work.
