### ISSUE TITLE
There is a way to give celery worker parameters?

### ISSUE THREAD

**Issue by alissonperez** [poise/application_python#76]
Hi,

I'm using application_celery_worker and I need to set `--concurrency` parameter, but I didn't found any place talking about parameters to celery service.

There is a way to set this parameter to celery service?

Thanks!

**Comment by coderanger** [comment]
There isn't a way to set command line arguments currently (though there probably should be), but you can set this in the `application_celery_config` resource (aka in the config file) via:

```ruby
celery_config do
  celeryd_concurrency 10
end
```

You can also subclass the celeryd worker resource and extend it to pass the command line arguments you want if you prefer that approach.
