### ISSUE TITLE
metadata.rb missing

### ISSUE THREAD

**Issue by bierdybard** [poise/application_python#80]
Hello,

My org maintains an internal supermarket with strict license restrictions, automated by checking the metadata.rb file. This repo doesn't have metadata.rb so I am not able to pull in the cookbook internally despite your licensing being compatible.

Would you please consider adding metadata.rb and tagging a new release?

Thank you!

**Comment by coderanger** [comment]
This is not a normal cookbook, the license is listed in the gemspec metadata. The cookbook form is a compiled artifact which I create during releases. You can find the cookbook version on the public Supermarket. Consuming pre-release versions is documented in the Halite readme but is not recommended.

**Comment by bierdybard** [comment]
I'm sorry, I misspoke. My repo maintainer was talking about metadata and I was looking at a metadata.rb file. I'm not looking to utilize prerelease software; the issue I'm encountering is that we have a hard license-based whitelist for external dependencies; we can only depend on items on the internal repo which are whitelisted by license.

The problem is that in the metadata.json in the compiled artifact, the license field reads "none" instead of "Apache 2.0", which is what my organization's whitelist filter is looking at. This is in contrast to your poise-python cookbook which shows this correctly. This is what I'm asking for a correction on.

Please let me know if I can clarify further.

**Comment by coderanger** [comment]
The current release predates me adding the license metadata (as well as many other things) in the Halite converter. It will show up when I do the next release automatically. I can't retroactively update old releases though, and current this repo's tests are red pending a new release of poise-service, which is pending about a half dozen other things.
